# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c40d15a1fa3d5d13140e364d99d806a04506c9c01e8d5ec96c26c0a0412c588614520c572ee50bb5815824840d73ba70d10e08e28735adad3c73d5f11eb82eb

test:
  secret_key_base: 1e741ed312eefd8753e85e89fb22a49f6587f42cc69938a3241f1028886136d1fb9ecdceffc50ec927817f99ab0451071d8ca22679e309d903698c8ef07ed80e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
